### ISSUE TITLE
Sync level

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#101]
I have a question about how the level of syncing works.  I can't seem to find the answers in the docs, apologies if I'm missing them.

- Symlinks, means just like an alias, so actually all the photos purely live in the main folders?
- When an album is deleted from GP, is that replicated locally when script is run?
- What happens when a photo is deleted from GP, is that also deleted local when the script is run?
- If a photo is re-edited in GP, will that get redownload/updated locally when the script is run?
- If a photo is downloaded, later put into an album, will the script create a new symlink?
- What happens to photos in archives?
- For backup purposes, if all live files are in the main folder, the albums folder can be disregarded if we are only considering backing up the raw files?

**Comment by gilesknap** [comment]
Reasonable questions, I shall start an FAQ with these:

- yes symlinks are pointers to another file so there is only one copy of each photo which resides in the root/photos/YYYY/MM folder and it may be linked from multiple albums
- The album tree is completely re-created when --flush-index option is used so, in this case, deleted albums would be removed. This is required because you have to force gphotos-sync to go back and rescan everything to notice missing files. Otherwise, it is only doing an incremental backup and therefore scanning for files added from the last time of backup. Note that recreating the album tree is pretty fast but scanning all of the files will take a while.
- when a photo is deleted it will not be removed from the local backup until you run gphotos-sync with --flush-index and --do-delete. Again these options override the default incremental only backup.
- photos re-edited in GP are not noticed by gphotos-sync unfortunately. It's a Google API restriction. See the known issues section of the readme. We need to sort this one out somehow - maybe saving the edited photo as a copy and deleting the original would work but not be ideal.
- If a photo is retrospectively placed in an album I think it will get added locally - need to check.
- I don't know what happens to photos in archives - it depends what google API delivers on mediaitems.list/search - we could check
- Yes for backup purposes you could only backup the photos folder but I would recommend that you then also backup the gphotos.sqlite folder otherwise you are not saving the information about what albums you created (and for me this was one of the main reasons that I wrote gphotos-sync).

I'm not 100% sure about all of the scenarios with album deletion etc. So I would appreciate it if you could respond if you find anything above incorrect. One thing that is not mentioned is that if you add new photos to an existing album that works and will change the folder name to reflect the new most recent album contents date.

If you want your local copy to most closely resemble your remote then you need to always run with --flush-index and --do-delete. This is perfectly OK but will take quite a bit longer. An incremental update is nearly instantaneous if no new files have been added.

I think there is some scope for improving things a little with respect to reflecting deletion and retrospective updates of albums with already downloaded files. Completely flushing the database seems a little drastic to achieve this. I have to go now but will continue this discussion soon.

**Comment by gilesknap** [comment]
I'm going to close this for the moment as I think the writeup from Linux Uprising covers most of what a new user will need to know. Please re-open if you feel there is a need for better documentation.
