### ISSUE TITLE
Store oauth token outside db dir

### ISSUE THREAD

**Issue by wtreur** [gilesknap/gphotos-sync#117]
I noticed the OAuth token is stored in the regular backup folder. However, I'm syncing the folder to an external (cloud) drive and from a security perspective, I'm not sure it's wise the token gets copied as well. I'm using a regular mount point in Linux to set up the external share, so excluding the token file is not an option, unfortunately. 

I don't have a lot of python experience but I should be able to change the path in https://github.com/gilesknap/gphotos-sync/blob/master/gphotos/Main.py#L193

However, which place is better suited? The config dir? Furthermore, what about backward compatibility? Should the script look for the 'old' place and then move the file?

What do you think?

In any case: Great work on this project. I'm glad there is a proper way to backup google photos after the photos-GDrive sync snafu from Google.

**Comment by wtreur** [comment]
Hmm. I noticed I can probably just work around this by setting the ``--db-path``, ``--albums-path`` and ``--photos-path``

**Comment by gilesknap** [comment]
In fact, you could just use --db-path. I place the token file as a peer to the DB wherever that is. So, specify the root folder on your cloud drive and the --db-path in a private area.

I suppose there would be some merit in allowing a separate configuration option for token location, just in case you were keen to back up the DB? Having said that, loss of the DB is not critical since it can be recreated easily enough - all important data is in the file system.
