### ISSUE TITLE
file dates and date taken

### ISSUE THREAD

**Issue by marcodings** [gilesknap/gphotos-sync#122]
Hi,

I'm synching  the photo's i got from gphotos to Lightrooom.

No i have 2 challenges.
- DateCreated is the time of sync which is kind of useless, i'd prefer if we could set "file creation date" to "file modification date"
- For those files that get synched that do NOT have a "date taken" set i'd like to set it to the "file modification date"

I'm sure i can find a workaround for this using exiftool etc but it would be much cleaner if if could be handled directly on sync.

Thanks for considering
Marco

**Comment by gilesknap** [comment]
Hi,
- I wrote this on Linux originally where most filesystems do not have 'create date' (incredibly). I can easily modify the code to set create date and modify date, so that those filesystems that support it will get create date set as you request.
- The date that I use comes from Google Photos metadata, I do not read the exif for normal sync since it would slow things down quite a bit (but I do inspect the exif dates when using the --compare-folder feature). So the date is whatever Google decides to extract and I imagine it uses 'date taken' but I have not checked. For your files with no 'date taken' exif, which date do you get?

**Comment by marcodings** [comment]
I get the metadata stuff i wrote som interfaces on php and processed "takeout" json on other occasions. ( just sucks google refuses to support location in metadata)

> For your files with no 'date taken' exif, which date do you get?
Well lightroom is "strange" it shows the creationdata in its metadata, hoewever when trying to filter on it the data is "not set", hence my desire to set the "date taken" which is used.

**Comment by gilesknap** [comment]
If I understand you correctly, you want to modify the exif on the
downloaded files?

This is a little outside of the remit of gphotos since it is supposed to
back up what is in your library.

I did experiment with scraping the GPS from google photos web and updating
the exif on the backed up files but this was an extra step. Adding anything
that messes with the file content would slow things down by an order of
magnitude. (the scraping approach has been closed off my Google now - I'm
looking at some alternative approaches, the crudest of which involves
Google Takeout)

It would be quite easy to write a post-processing utility to do achieve
what you want.

**Comment by marcodings** [comment]
I understand and i can write a postprocessing task.. my reason for requesting integration is to not messing up the "recognition" for built in comparision and GPS updates.

I have used The json's in takeout to "recover" some 74000 local files for a friend that were severly messed up. It's what happens when people whith a "little" knowledge attempt to help.

Once takoute has downloaded its easy, my "problem" was that a large set takes a very long time

**Comment by gilesknap** [comment]
Ok I think I see what you are getting at. I don't have a major issue with getting gphotos to clean up exif. But it would need to be an optional feature that is recognized as causing much slower sync since it will need to read in the exif of every file and potentially write some changes. 

I did a very crude fix of all of the exif of my library (going back to 1997) before I uploaded it to Google in the first place. So have looked at this sorry if thing before.

**Comment by marcodings** [comment]
optional is just fine..
It would only need to write exif datetaken it if its not there typically whatsapp images screen caputures. in my experience the atual photographs woult have the correct exif info

As for the modificationdate that is at "file level" should not significantly slow stuff down

**Comment by gilesknap** [comment]
Here is why it will slow down things a great deal, in fact, it will slow
things down just as much as doing it as a post-processing step.

The steps to achieve this are:-

   1. Google provides an HTTP address for the photo
   2. I stream from that address directly into a file. It's just a blob as
   far as the HTTP 'requests' library is concerned
   3. I open the file and read it into memory and ask the EXIF library to
   interpret the EXIF
   4. I see if there is a date taken and add one if not
   5. I write back out the file with new EXIF using the EXIF library

Step 5 is non-trivial because my chosen EXIF library currently does not
support adding new fields (I volunteered to fix this some time ago but have
not got around to it).

I thought I'd write this out in full because I'm still not sure if you and
I are talking about the same issue. Does the above make sense for your
requirement?

Thanks

**Comment by gilesknap** [comment]
I have added the setting of creation date for the Windows platform. See latest in master. Will roll into the next release.

**Comment by marcodings** [comment]
Ty.. Will do
