### ISSUE TITLE
Remove source photo after download

### ISSUE THREAD

**Issue by jamesread** [gilesknap/gphotos-sync#142]
Hey. Thanks for your work on this tool so far, it's the first one that seems to work well for me to get over 100Gb out of Google Photos in a sensible way.

My use case is just that - getting stuff *out* of Google photos. While the tool downloads copies of the photos nicely, my use case is to reduce my dependency on Google photos, and merely use it as conduit for getting photos off of Android devices. Manually working out which photos have been downloaded and deleting accordingly is very error prone, and I just have too many photos to do that realistically. 

Would you consider adding a `--remove-after-download` flag or similar to this tool? 

If there is a way of doing that today I didn't stumble across it after going through the project readme and --help.

**Comment by gilesknap** [comment]
Hi James,

I'm keeping gphotos-sync read-only for the foreseeable future. One of the reasons is that the Google Photos API is too crippled to do a good job of any two-way features. Indeed, one of the things it cannot do is delete files and Google has publicly stated that they will not fix this https://issuetracker.google.com/issues/109759781. 

So I'm afraid this cannot be done.

You could almost work out a sensible workflow using gphotos-sync. In fact, all you need to do is convince yourself that it is trustworthy and just delete your files from Google after sync. Just make sure you don't use the do-delete flag. BUT this would not satisfy me because of other Google API limitations which mean that:-

- All videos are transcoded to lower quality, (because of higher compression)
- no GPS data in your images
- No burst shots are synchronised
- Any edits in the Google Photos Web are not synchronised

I use gphotos-sync to keep an eye on my library and verify that I or Google have not accidentally deleted any images. I also want to be able to exit if it becomes necessary. If that day comes then I'll be downloading a Google Takeout and writing some code to parse it, so not using gphotos-sync (unless Google fixes all of the above).

I think for your use case you would be better to turn off google photos backup and use a third party like dropbox which can auto-backup your phone's photos. You can sync that to your PC and move it to your backing store, so you would only need  enough Dropbox space to last between moves (so probably free service would do).

**Comment by jamesread** [comment]
Hey @gilesknap, thanks for explaining why this feature cannot be implemented, and sharing more of the Google photos API limitations (I didn't know about videos being transcoded to lower quality, but had come across the other issues). 

Time to manually drag stuff off my android devices, and switch to another service that preserves the originals as you suggest!

**Comment by gilesknap** [comment]
Just one last point. You don't need to manually drag anything. I used to
use dropbox for android and that will copy photos out for you
automatically. I'm sure other 3rd party storage solutions would do the same.
