### ISSUE TITLE
Looking for a way to sync albums without downloading pictures

### ISSUE THREAD

**Issue by ballle98** [gilesknap/gphotos-sync#152]
Excellent program.  Thank you for creating this.  I have my photos on my computer organized into directories and albums.  Is there a way to sync those directories as albums in google photos?  I don't want to download 100K photos that are already on my computer.  Is there a way to skip that step?

**Comment by gilesknap** [comment]
Hi, I'm afraid there is no simple way to do that at the moment.

It would be a bit of effort to create such a feature and I'd always be worried that the matching algorithm had not caught all the missing files. So would not be sure I had a full backup.

On my home connection, my 100,000 file collection only takes about 6 hours to download in full so I'm afraid I am not likely to be working on a solution for this.

**Comment by gilesknap** [comment]
By the way. Do your local directories and albums match what you have in Google or do they predate you uploading to Google? I have the latter situation and I tagged all of my photos before uploading so that one day I can re-create the original pre-Google folders as albums. Currently, API restrictions make this impractical. If I leave Google or the API improves then I will write the code needed to restore these 'pre-Google albums'.

**Comment by ballle98** [comment]
My directories and albums predate uploading then to Google photos.  My thought was to use inventory the items in Google and match them to the local items.  So that for a local item I can get a media id and add it to albums that I create for local directories using this API:

https://developers.google.com/photos/library/guides/manage-albums

**Comment by gilesknap** [comment]
So I have done some work with the matching part. If you look at the
comparison feature of gphotos-sync, it attempts to compare what has been
downloaded from google with a pre-existing collection of media items. It
does require that the files are downloaded for comparison because it looks
inside them for EXIF info - the Google supplied metadata is not good enough
to make reliable matches.

So, in theory, we could re-use this logic for your use case and indeed I
have the same use case, I would like my old folder structure represented in
Google albums.

HOWEVER. The Google API is too crippled to do this, you can only put an
item in an album by specifying the album at upload time. It is a very
limiting restriction, I'm not sure we will see this fixed in the near term.

**Comment by gilesknap** [comment]
Closing this for the moment. If the API ever gets fixed I will address the issue of creating albums from local folders (but it will likely be a separate project since gphotos-sync is strictly read only)
