### ISSUE TITLE
Not getting photos from "shared" contacts

### ISSUE THREAD

**Issue by djsmiley2k** [gilesknap/gphotos-sync#156]
Hi,

So my wife and I have our collections synced to each other by way of the google photos sharing function that allows you to share your entire photo collection with someone else.

In the past, I used to back up the photos directly from gdrive, and that would include the photos in the shared directory/album.

I've just started using this tool due to the fact the gdrive method no longer works (great work btw!) however, looking at my 'old' collection, removing all the dupes and then comparing it to my existing sync made with gphotos-sync it appears it doesn't include this shared album in the download?

(I've also got ~30k bad ID's, so I don't know if this is related.).

Is this something you can add? - From the website, I can see her photos in my standard 'stream' or by going to https://photos.google.com/partner/ which shows only her photos.

**Comment by djsmiley2k** [comment]
I've just realised, I managed to max out my quota for today - so this might be the cause. I'll have to re-test once enough time has passed that my quota isn't exceeded and see how I get on.

**Comment by gilesknap** [comment]
Hi,

I have not used the sharing feature and I'm not sure how the Google API treats photos shared this way. Your quota problem may be the issue though. Unfortunately, gphotos-sync treats quota errors as 'bad-ids' so you will need to delete your bad IDs file or those files will always be ignored.

I intend to remove the bad ids feature and always report errors because the bug that bad-ids was intended for has been fixed by Google.

Let me know how you get on and I'll look into this if you are not receiving your shared files.

**Comment by djsmiley2k** [comment]
Ok.

I ran the script again today, after removing the bad id's file and it 's picked up all my photos including those shared from my wifes phone. :)

**Comment by gilesknap** [comment]
That's great, thanks for letting me know.
