### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by michael79bxl** [gilesknap/gphotos-sync#159]
Hi,

Is it possible to add a `--progress` option that would output a percentage of the progress of downloading photos?

eg. result: WARNING Downloading Photos ... 79%

Regards,

Michael

**Comment by gilesknap** [comment]
Yes, I'll put this on the todo list.

**Comment by gilesknap** [comment]
@michael79bxl I have added a progress indicator. The change is in master.

It does not show a percentage because I do not strictly know how many files need to be downloaded since I check each one, in turn, to see if it is already there or not. Hence I just have an incrementing file count which does give some feedback.

Let me know if you have ideas for improvements.

**Comment by gilesknap** [comment]
Closing for now.
