### ISSUE TITLE
Database folder on mounted network drive (AFP)

### ISSUE THREAD

**Issue by phifogg** [gilesknap/gphotos-sync#167]
Hi,
I am setting up gphotos sync on my mac server running OSX High Sierra with Pything 3.8. Setup was a breeze :)
Now I have also a NAS system and I use OSX's automount to map a directory /mnt/backup.

As I have multiple gphoto accounts for the family I thought it be great to store all the different configs in /etc. Created a folder /etc/gphotos-sync/<account>. Here is the pipenv area where I keep the gphotos.token etc. Runing 'pipenv run gphotos-sync /mnt/backup/...' I always get an error just after creating the gphotos.lock file. The error is 'database is locked'.

I know for sure this is not the case. :)

As an interim solution I sym-linkes the photos and albums folders from /etc/gphotos-sync/<account> which is a local directory. Et voila, it works like charm.

Something in the locking piece on a mounted (AFP) network drive is not as it should. Unfortunately I am not a python guy and thus cannot really work on the code :/

Hope the detail here helps, if I can do anything to help/debug, please let me know.

Fogg

**Comment by gilesknap** [comment]
Hi, Thanks for the detailed report.

I am already aware that file locking fails for NFS mounted drives and it
does not surprise me that AFP exhibits the same.

Instead of using the symlinks you can use the option --db-path to specify
where the database and its lock file are located. It is good for
performance to have this on a local drive anyway.

I think I need to add this info to the known issues section.

**Comment by phifogg** [comment]
Awesome, thanks for that hint. Works like charm with --db-path 👯‍♂ 

Now i need to work on a LaunchDaemon config to make this run scheduled. Once done I am happy to share this here.

**Comment by gilesknap** [comment]
@phifogg thanks, please do share your experiences. Lots of users of this tool are working with NAS.

Closing this as 'can't fix but have a workaround'
