### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by abkierstein** [gilesknap/gphotos-sync#181]
Hey folks - thanks for creating and maintaining this project. Do you have a donation link so I can buy you a beer?

**Comment by gilesknap** [comment]
Hey, thanks for the offer, but I have no donation link.

I do this out of interest in learning about Python and because I personally want a solution for backing up my Google Photos Library. Also, open-source software for me demonstrates a really positive side of human nature and I enjoy being part of that.
