### ISSUE TITLE
Lower quality downloads?

### ISSUE THREAD

**Issue by ozupey** [gilesknap/gphotos-sync#203]
Does gphotos-sync not download the files in original quality? I have a lot of 4 GB videos recorded in 4K at 60 FPS, but when downloaded, they end up a lot smaller (roughly 50-200 MB) in 1080p at 30 FPS.

In Google Photos:

<img width="255" alt="Screenshot 2020-02-28 at 01 10 23" src="https://user-images.githubusercontent.com/44553515/75467974-6ff65500-59c7-11ea-9739-d318ae5dfd17.png">

Downloaded by gphotos-sync:

<img width="259" alt="Screenshot 2020-02-28 at 01 13 28" src="https://user-images.githubusercontent.com/44553515/75468042-8d2b2380-59c7-11ea-8f21-32862792a621.png">
<img width="511" alt="Screenshot 2020-02-28 at 01 12 26" src="https://user-images.githubusercontent.com/44553515/75467983-71c01880-59c7-11ea-9aae-cba173f8aa11.png">

**Comment by ozupey** [comment]
Sorry, I totally missed it listed here:
https://github.com/gilesknap/gphotos-sync/issues/119

I guess I'll just have to use Google Takeout for these files. :)

**Comment by ozupey** [comment]
Sorry, I totally missed it listed here: #119

I guess I'll just have to use Google Takeout for these files. :)

**Comment by gilesknap** [comment]
Yep, this really sucks and Google seems to be sitting on. They do have takeout for data law compliance but it is clunky. I'm of the opinion they don't want to give us total control of our data on their servers (GPS tags is a another example).

Note that there are two things happening:-

- 1st if you are using the free service then your files get converted to 'High Quality'. I'm pretty OK with the differences between originals and High Quality. But might not be if I was taking 4K video - I just checked here https://support.google.com/photos/answer/6220791?co=GENIE.Platform%3DDesktop&hl=en and they say 1080p is the max.

- 2nd when you download videos using the API there is a =dv parameter which is supposed to get the file as-is from the library but it always does a transcode. This really needs to be fixed but Google is not responding to the ticket.

By the way, are you paying for Google storage? If not I guess your 4K videos were downsized on the upload already.

There is a possible workaround for the =dv download issue which is to use some javascript to drive the GUI and get the videos that way. @michael79bxl was making good progress on this, see https://github.com/michael79bxl/gphotos-sync-ui.

**Comment by ozupey** [comment]
Yes, I have a business Gsuite account for the storage. Everything is uploaded in original quality. 

Just waiting for my Google Takeout to be finished processing (36 hours so far). I believe the easiest way to do this would be to use Google Takeout, pick the "Store in Drive" option, and then use rclone to sync the folder it creates. 

I'll keep you up to date. :)

**Comment by gilesknap** [comment]
> Just waiting for my Google Takeout to be finished processing (36 hours so far). I believe the easiest way to do this would be to use Google Takeout, pick the "Store in Drive" option, and then use rclone to sync the folder it creates.

The easiest way for people with a massive amount of Google storage :-)


You will find that takeout for Google Photos is a bit of a mess. All your files and meta-data are in there but not in a friendly form. One day I'm going to write a Python script to convert takeout to a gphotos-sync-like folder structure. But that is probably when I decide to abandon Google Photos for good. 

My long term strategy is this:-
- Have Google Photos as my primary photos store and manager because it is so damn good
- Use gphotos sync as an 'almost' backup but in particular to verify that no unexpected deletes or other changes have occurred. (I nearly silently lost many photos during the days when Drive integration was enabled and I was using InSync to sync my photos to local disk)
- Put up with the inadequacies of the Google Photos API until one of the following happens:-
  - they fix the API and gphotos-sync is able to do a true backup
  - I give up because a better service comes along or Google's data control freakiness gets to be too much. At this point, I will use takeout and abandon ship.
