### ISSUE TITLE
is it possible to use API keys?

### ISSUE THREAD

**Issue by tchwpkgorg** [gilesknap/gphotos-sync#205]
Can gphotos-sync use API keys?

I find setting up OAuth 2.0 Client IDs very confusing; it needs a consent screen, which is hard to do and which needs a review from Google, which costs money.

API keys don't have these drawbacks.

**Comment by gilesknap** [comment]
In order to use the Google Photos API we need a client secret key for the application to talk to the API. Then we need an authorization token to allow access to an individual's data.

The consent screen is an essential part of the authorization and there is no way around that.

The client secret would be embedded in a commercial product but all API calls would go against a single quota and that would result in charges for use of the API.

Instead of this, I ask every individual user to create their own client secret so that each gets their own quota. The free quota is easily enough to download more than 500,000 items a day.

Unfortunately, the setup of the client secret and user token is a little fiddly. However, it only needs to be done once since we cache a refresh token and this can be reused indefinitely. 

I assert that this is the only way to use the API in a free product. However, if you are aware that a simpler scheme is possible please explain and I'll be happy to implement it.

**Comment by tchwpkgorg** [comment]
I see. What about service accounts? Do they have the same limitations?

**Comment by gilesknap** [comment]
I've just had a quick read on service accounts.

I think it comes down to the same problem. If I chose to run a service on Google cloud, I could provide an interface to the Google Photos API. But I would be subject to fees for the use of the API because all users of gphotos-sync in combination would far exceed the free quota.

**Comment by gilesknap** [comment]
Closing as can't fix. Please reopen if you have any further ideas.
