### ISSUE TITLE
Why do you need to create a virtual env to use gphotos-sync?

### ISSUE THREAD

**Issue by ikwyl6** [gilesknap/gphotos-sync#206]
Hi more of a discussion topic than anything else - I've read about virtual envionrments and I see the reasoning for using one, but does ```gphotos-sync``` have to use older or development site-packages in order to work? is that why it is stated you should create one before using gphotos-sync?

I couldn't find a requirements.txt file that can tell me what pkgs are needed that are not 'typical' or standard compared when installing dependencies using pip..

**Comment by gilesknap** [comment]
Hi @ikwyl6.

There is no requirements.txt because we use pipenv for dependency management. You can look in Pipfile to see the list of dependencies.

In general, it is not a good idea to install packages into your system python instance because you will soon hit some kind of dependency clash if you do that for every python application you install. Besides, Python is used by the OS these days for various management tasks and you can break your OS if you are not too careful.  

Thus using virtual environments is recommended. We use Pipenv which attempts to hide the problem of managing virtual environments from the user by associating venvs with the folder you are executing from.

HTH

**Comment by gilesknap** [comment]
closing - feel free to continue the discussion if needed
