### ISSUE TITLE
Sort backed up files

### ISSUE THREAD

**Issue by arewm** [gilesknap/gphotos-sync#21]
Your modifications to the original script are useful, but I have an enhancement request.

I think it would be even better if you sorted the photos backed up to the `drive` folder into a year/month/day folder hierarchy like those in the `picasa` folder. This does not need to persist back to Google Drive, but having it as a local organization would greatly increase the usability of my local backup!

Do you think this functionality would fit in with the utility, or is it out of scope? I might try to tackle this if I have some time. Would you like me to submit a pull request if I do?

**Comment by gilesknap** [comment]
Hi, yes this would be within the scope of the project.

The original did this anyway and I moved away from it because (a) it caused lots of duplicates for burst shots where many photos were taken in the same second (b) I wanted to compare results with Google backup and sync to verify that I was syncing all files.

The code now handles duplicates anyway (by adding (1) (2) etc ... so it would be fine to have an option as you suggest. I would want it to be an option though and still be able to choose to have the original google drive file folder structure.

I've stopped actively working on this project for the moment but would be happy to review pull requests. I should warn you of the reasons for stopping and see if you still want to put it the effort:-
- I'm now using Insync to continually two-way synchronize my google drive and it is very good (but does not do the photo albums)
-  There are lots of issues with the Picassa API which make this project not work perfectly, these are discussed in the readme to some extent and also in https://github.com/gilesknap/gphotos-sync/blob/master/etc/DriveAndPhotos.rst. I do have ideas for workarounds for some of these but none are ideal

Cheers,
   giles.

**Comment by arewm** [comment]
Sounds good.

Instead of making an option to backup with this file structure (or not back up with it), I was thinking about making an option/directive to toggle the backup folder hierarchy format. This would set some setting which will then be referenced whenever a backup is initialized.

Insync does seem to be pretty powerful, but I do not need to backup my entire drive, just my photos (also, I don't want to pay! [: ).

**Comment by gilesknap** [comment]
I don't quite understand the distinction you are describing. Never the less, if you add a feature without removing the original capability that would be fine.

One easy way to achieve what you want might be to leave the files alone and build a set of symlinks to them in the structure that you want. This would be in keeping with the way the albums are done.

**Comment by gilesknap** [comment]
@arewm the new 2.0 version no longer looks at drive but instead directly at the google photos library. This has no folders so I have restored the folder hierarch of YYYY/MM by created date of the items.

I think this gives you what you wanted. Closing the ticket.
