### ISSUE TITLE
New images not being indexed or downloading

### ISSUE THREAD

**Issue by LootenPlunder** [gilesknap/gphotos-sync#222]
I have gphotos-sync set up on windows. It's set to sync nightly which it does just fine. I took a bunch of photos yesterday, and last night it synced and downloaded all of them. 

Today I took a few pictures, confirmed that they showed up in google photos, confirmed my api setup/quota on google cloud, yet the script runs with no errors in the log and 'indexed 0 items'. Today's photos just don't show up in the index and are subsequently not downloaded. 

The system time didn't change and the time in the log is correct. Is there some kind of lag between an item showing up in photos.google.com and being available via API media search?

**Comment by gilesknap** [comment]
Hi, I believe there is a lag, but that it should be a few minutes.

If the issue persists then it would be interesting to see what happens if you use --rescan. This removes the date filter that gphotos uses to do incremental backup.

I have a nagging feeling there could be a timezone issue, since I think I recall that the date range I use is in whole days. To see if this is likely, you could check the file dates on your filesystem against the photo date and report the difference to me (and which timezone you are in).

Also see #66.

**Comment by LootenPlunder** [comment]
So the image did eventually download on the scheduled overnight sync.

The exif time and date on google photos matches the exif on my local machine (~2pm eastern). The file created/modified time is 4 hours later which is weird since I think it synced early the next morning. Is that what you were expecting? I'm Eastern Time if that helps.

I read #66 and that might be it. If I have to wait 1 hour for the sync to work that should be OK generally. I'm happy to close for now and I'll report back if something else crops up.

Thank you for this project by the way, it completely saved my workflow.
