### ISSUE TITLE
please add a requirements.txt file

### ISSUE THREAD

**Issue by jorythompson** [gilesknap/gphotos-sync#226]
This would make installation much easier!  I am trying to install one module at a time and am having problems with:
`ImportError: cannot import name 'dataclass' from 'attr' (/usr/local/lib/python3.7/dist-packages/attr.py)`

I did install attr with:
`pip install attr
`
Any suggestions?

**Comment by gilesknap** [comment]
Hi Jordan,

Some time ago I switched to using pipenv instead of requirements.txt. To install pipenv for your user simply do the following:

- pip install --user pipenv
- make sure that /home/${USER}/.local/.bin is in your path
  - on Ubuntu and probably on Raspbian the .profile script already detects that bin folder and adds it to the path so you may only need to logout and login again
- now you are ready to create a venv
  - cd to gphotos-sync
  - pipenv install
- to activate
  - pipenv shell

If you can't install pipenv for any reason then you should be good to just create a virtual environment and run ```python setup.py```. That should pull in all the (runtime) dependencies for you.

Regarding attr I too suffered for some time working out this issue. Although the namespace is attr the package you want to install is called attrs. You need to make sure you have removed attr as well since there is a name clash.

**Comment by jorythompson** [comment]
Hi Giles,
thanks for your suggestions.  I have it running and have sent you some logs.

thanks for your continued support with this,
Jordan

**Comment by gilesknap** [comment]
Hi Jordan. I don't seem to have received any logs.

**Comment by jorythompson** [comment]
Should be in a different email
