### ISSUE TITLE
gphotos-sync doesn't backup all images in date range.

### ISSUE THREAD

**Issue by shirha** [gilesknap/gphotos-sync#242]
**Describe the bug**
For my first run I took a small sample of my images on google photos and tried to back them up. [RaiDrive](https://www.guidingtech.com/download-all-google-photos-albums-computer/) creates a network drive of google photos and shows 3 months 06, 07, 12 but gphotos-sync skipped 06 plus some in 12. 

**To Reproduce**
`gphotos-sync --skip-albums --start-date 2000-01-01 --end-date 2000-12-31 e:\gphotos-sync`  does not back up folder 2000.06 and skips some in 2000.12. I have 21k images uploaded and I was afraid of running into the request limit if I just let it run full scan. I was wondering if there is a way to get a log of all the images without actually downloading them all. The missing images might show up. I need to reconcile this before I feel comfortable using it. I do realize you are depending on the google photos api. RaiDrive shares the request quota with everyone using their app so I was only able to copy about 100 images off the network drive before it quit working. They don't allow you to supply your own credentials.

Attach is a zip containing the gphotos.log, one of the missing images info and a compare between gphotos-sync and RaiDrive. 

[docs.zip](https://github.com/gilesknap/gphotos-sync/files/4708373/docs.zip)

**Comment by gilesknap** [comment]
Hi @shirha thanks for a detailed report. This issue is very interesting and I'm very keen to get to the bottom of it since it is obviously important that all photos are backed up and it is hard to check that this is the case.

We have investigated a few issues along these lines before and it has turned out to be a Google API problem, for the most part I have implemented workarounds (and reported the bugs to Google but none of these are fixed yet).

Now in this case RaiDrive is using the API too so I wonder what the difference is?

In bug #89 I discovered that for some libraries, some photos would never get indexed unless I indexed their albums, so one thing you can try is the same command but not use --skip-albums.

Regarding indexing all without downloading there is ```--index-only``` argument. You can see what is indexed by looking in gphotos.sqlite but you will need sqlite3 and a little SQL knowledge. Also the log file does list every file it indexes and I can see that no files from 2000/06 were indexed.

You should be good to download all photos on free quota, I have 120k photos and 100Mbps connection and can download the whole library in a few hours without quota issues (if your connection is very very fast then there could be an issue - in this case reducing the number of threads will mitigate)

**Comment by shirha** [comment]
Just a clarification - did you mean "**unless** your connection is very very fast"? What is the default number of threads? Neither the -help message or the logs mention it. Also, I'm going to just run the full scan with albums and report back with a directory compare. Thank for your very helpful info.

**Comment by shirha** [comment]
I just figured out my problem! The photos I want to backup are under my wife's account, not mine! Mine is missing month 2000/06 plus some in 2000/12! Sorry for creating a problem for you.

**Comment by gilesknap** [comment]
No worries. If your connection is fast then you can hit the download quota more quickly. I think default threads is 10, I should add that to the help text.
