### ISSUE TITLE
All tests failing

### ISSUE THREAD

**Issue by dgrant** [gilesknap/gphotos-sync#26]
Not sure why, but all tests are failing locally and in Travis.

**Comment by gilesknap** [comment]
From the logs it looks like the tests are running OK but possibly the example account it uses has had its photos moved around since I last did a build. I was investigating replacing httplib with requests when I was last looking at this code so may have left the test account in bad state.

I'll need a little time to investigate this and am off on holiday soon so it will be a few weeks.

**Comment by gilesknap** [comment]
This project needs a review of the test approach. However I'm not actively developing any more since the picassa API deprecation has defeated me for the moment.

**Comment by gilesknap** [comment]
The tests have been re-written and are now working. However, coverage is poor and the tests do need expanding.
