### ISSUE TITLE
Disable symlink and hardlink

### ISSUE THREAD

**Issue by hadim** [gilesknap/gphotos-sync#281]
Is that possible to disable symlink and hardlink and instead have the photos duplicated in between photos and albums?

**Comment by gilesknap** [comment]
it is not currently supported and would require code changes. one big problem is that in order to avoid sync issues I currently delete  and recreate the whole of the albums folder whenever any changes have occurred. Since they are links it is inexpensive to recreate them all. Some solution to this problem would be required if we supported copies in folders.

What is the motivation for this?

**Comment by hadim** [comment]
I backup my photos on a Google Drive folder using Insync (on Linux). I prefer to have those files duplicated instead of linked together in Drive since sym/hard links are not really supported on GDrive.

**Comment by gilesknap** [comment]
I use Insync on Linux too but I do not back up my photos to there since it feel like if Google data centers had some kind of catastrophe that I'd have my photos backed up twice to the same vendor.

I just tried soft links in a synced folder and it appears to just ignore them.

The soft links in album folders are really just an on disk representation of the information that is always stored in the database, on every sync I completely tear down the albums folder and rebuild again from info in the database. Thus I assert you would be OK not backing up the albums folder.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
