### ISSUE TITLE
database locked, trying to move

### ISSUE THREAD

**Issue by paulmorabito** [gilesknap/gphotos-sync#339]
Hi,

I'm using the latest version via docker. I am trying to sync but repeatedly getting a file locked error on the sqlite database. This seems to be as a result of the volume being mounted by CIFS. I moved the db file and the lock file to local storage (mounted as  /config in the container) and then tried to re-run with the --db-path=/config added to the sync.

Instead of it running the sync I got another request to visit a URL and re-validate the security token. Is this the correct behavior? I'm hesitant to continue in case it resets everything as it took a long time to get my whole archive of photos down.

**Comment by gilesknap** [comment]
Sorry for the late reply.

I think the cause of your issue is that moving the DB also moves the other files such as .ghotos.token. If you copy that file then all should be well.

In addition, if you did re-authenticate it would still be able to use the existing db file for incremental update anyway.
