### ISSUE TITLE
Multiple accounst

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#35]
Ability to synchronize 2+ separate photos accounts without having to reauthorize requestes

**Comment by gilesknap** [comment]
This is an upcoming feature. I intend to store the Oauth2 token in the sync root folder (with appropriate access permissions) instead of having a global one for the application.

In the meantime, you can synchronize as many accounts as you like (to different sync roots) but will need to use --new-token and go through authentication/authorization every time.

**Comment by gilesknap** [comment]
This is now done in master. The token file is stored in the root of the sync.

**Comment by apatternjugglers** [comment]
> 
> 
> This is now done in master. The token file is stored in the root of the sync.

Hi -new user and so far my first sync is going OK.  Thanks for your awesome work.
When I come to add the second account, from this issue do I understand correctly that I just use --new-token  when syncing to the second destination,  and its token will be retained there for all future syncs with the second dest? 
Thanks!

**Comment by gilesknap** [comment]
Hi, yes you can sync two different accounts to two different folders as you
suggest. You don't need to specify --new-token because when you specify the
second root folder it will see no token there and request a new one anyway.
