### ISSUE TITLE
Comparison to rclone with google-photos backend

### ISSUE THREAD

**Issue by wscott** [gilesknap/gphotos-sync#446]
One other option for downloading photos is to use the google-photos backend of rclone to download pictures.  I don't find anyone that compares photos-sync with rclone. It would be nice to link to a page/issue/wiki from the top-level Readme with a comparison.

Background:
I have used gphotos-sync in the past in a cron, but have recently been using TrueNAS-Scale and they have rclone support built in. I wonder if that sync would be equivalent or if I should set up some container to continue using gphotos-sync.

**Comment by gilesknap** [comment]
This is a good question. If you are going to try both then please post your findings and I'll add it into the documentation.

I've not looked at rclone and I wonder how they handle the many limitations of The Google Photos API given they do two way sync as I understand it.

**Comment by gilesknap** [comment]
So I have taken a brief look at this
https://rclone.org/googlephotos/
I'd say that the features are similar.

-  it looks like it download duplicates of files in albums instead of using links.
- it is a way more widely used and supported project - gphotos-sync is a one person project
- I think the documentation is a little more complete for gphotos-sync
- I don't understand how rclone is creating the oauth secret - not sure how that bit works - this would need more reading
- rclone is obviously hamstringed by all the same google API issues we have here
- rclone allows upload but that is severly limited by google API
