### ISSUE TITLE
RFE: add an option to use a `YY/MM/DD` directory structure in `photos/`

### ISSUE THREAD

**Issue by kcgthb** [gilesknap/gphotos-sync#80]
Some people (^_^) take very large number of pictures on single days, and having all of the photos from the same month in the same directory in `photos/` can sometimes result in less than optimal situations, both from a filesystem performance and usability perspectives.

It would be great to have a command line option to use an extra depth level for the day the picture were taken (like `photos/YY/MM/DD`) to get a more granular directory structure.

**Comment by gilesknap** [comment]
This would also not be hard to do.
- pass a new option down to GooglePhotosIndex and to GoogleAlbumsSync
- Then, when creating new items, pass it on to set_path_by_date function in BaseMedia
- add your pattern in set_path_by_date function

I think it would be nice to record in the DB that this option had been used and disallow switching between YY/MM and YY/MM/DD in the same DB, otherwise you could end up with two sets of files at different folder levels.

I also think it is a good idea and might even make it the default (with a graceful switch to YY/MM for old DBs). One of the hardest things to cope with is duplicate file names and more folders would make this rarer.

For both #79 and #80 I'm happy to implement soonish. Also happy to let you have a go if you are interested. These should both be a good introduction into the code.

**Comment by kcgthb** [comment]
I may leave this one to you, it's more involved, and you may have a better idea on how you want to approach this.

**Comment by gilesknap** [comment]
OK, will look at this in the next few weeks.
I think it needs combining with --use-flat-path (which another contributor added - I guess they take fewer photos than you!)

**Comment by gilesknap** [comment]
I'm thinking these options should be combined into something like:
`gphotos-sync --folder-levels 3`
Where
1 = photos/YYYY
2 = photos/YYYY/MM
3 = photos/YYYY/MM/DD

I could instead have the parameters supply a pattern. However, I like the idea of a fixed list because then I would be able to automatically restructure previous downloads to the requested folder level layout instead of restricting the change.

@kcgthb any thoughts?

**Comment by kcgthb** [comment]
I think a user-supplied pattern would offer more flexibility, but then it would maybe be too much, I can already see user asking for folder structures based on location-based tags or camera model, who knows?

So a fixed list is probably better, although rather than calling the options 1, 2, 3, I'd go with something like: `--folder-level [Y|M|D]`, just to be a little more descriptive.

My $0.02.

**Comment by gilesknap** [comment]
I like [Y|M|D].

**Comment by gilesknap** [comment]
One further thought. Although automatic restructuring is a nice idea, there is a nasty issue. Duplicate file names are handled by adding a numeric suffix in the order that they are delivered by the API. There are all sorts of issues with this and restructuring would be affected so could not easily be guaranteed to be safe.

**Comment by kcgthb** [comment]
Indeed. So maybe it could be a more static config stored in the DB, with a check to see if a directory structure has already been created and check that it matches the config?

**Comment by gilesknap** [comment]
I'm going to have a think about how the duplicates are handled. This is a constant issue (and has been for all approaches to synchronizing photos that I used before developing gphotos).

If I can make a reliable method of handling duplicates then this folder structure feature could be more useful and robust.

**Comment by gilesknap** [comment]
This now depends on #86 (which is quite a significant change)

**Comment by gilesknap** [comment]
Apologies for the lack of progress. I need a good chunk of time to tackle #86 and its not going to happen for a few weeks.

**Comment by jcress** [comment]
this may be off topic, adding an additional enhancement request;
can there be an option to download albums without any dates in the path at all? 
i.e. 
/albums/catpics
in lieu of 
albums/YYYY/'MMDD catpics'

i'd like to use gphotos-sync to automatically pull new files into a directory with a predictable name so I can symlink it to my /www/ folder for inclusion on my pelican blog

**Comment by gilesknap** [comment]
It sounds like I need to implement some kind of regex system to allow
people to have whatever folder hierarchy they fancy.

I'm ok to add this but do need to implement the robust filename uniqueness
first and come up with a mechanism for coping with requests to change the
layout.

I'll likely get this in a few weeks.

**Comment by gilesknap** [comment]
OK, I have to admit that I'm never going to get to this issue. Its really complex and hard to test, plus Google's lack of movement on #119 means that there is reduced interest in solving it. Closing until something major changes.
