### ISSUE TITLE
Auto backup

### ISSUE THREAD

**Issue by Tyree** [gilesknap/gphotos-sync#85]
I assume I should set up a bat file in Windows to auto sync Photos. What command should I set in the batch file? Just gphotos-sync "TARGET DIRECTORY" or is there another command that is best for just getting new items?

Thanks!

**Comment by gilesknap** [comment]
Yep, the default options back everything up, so that should be all you need. Note that there is a lock file so if you end up running two instances one of them will exit cleanly - thus background sync is fine.

My Linux cron file runs this script:
`cd /media/Data/GilesPhotos/gphotos-code
/home/giles/.local/bin/pipenv run ./gphotos-sync  /media/Data/GilesPhotos/ >> /home/giles/logs/gphotos.log --logfile /tmp 2>&1`

So default options except that I pipe to a detailed log file so I can review if all is well.

**Comment by gilesknap** [comment]
`or is there another command that is best for just getting new items?`

The default option is to only look for files newer than the date of the last scan - it is really quick if there are no new files.

**Comment by Tyree** [comment]
Thanks, Giles!
Is there a way to limit the sync to just a certain folder (year)? With the old Photos to Drive sync that Google had disabled, I was only syncing the current year from Google drive via Backup and Sync. That saved room on my local PC. I have all older photos on a NAS. I assume if I just delete older years from the current sync folder that gphotos-sync will just download them again?

**Comment by gilesknap** [comment]
Sure, see the option --start-date. Also if you use the default options it
only scans for files from the last scan date anyway. So unless you use
--rescan it won't notice if you remove older files.

(If you run with --help it will list all the options.)

**Comment by gilesknap** [comment]
Closing this issue. Please re-open if you still need more info.
